// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PogodaAPI;

#nullable disable

namespace PogodaAPI.Migrations
{
    [DbContext(typeof(DanePogodowe))]
    [Migration("20240327170246_Init5")]
    partial class Init5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("PogodaAPI.ZapisPogody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("data")
                        .HasColumnType("TEXT");

                    b.Property<string>("miasto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("temperatura")
                        .HasColumnType("REAL");

                    b.Property<double>("wiatr")
                        .HasColumnType("REAL");

                    b.Property<double>("wilgotnosc")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ZapisyPogody");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            miasto = "Warszawa",
                            temperatura = 21.370000000000001,
                            wiatr = 1.1000000000000001,
                            wilgotnosc = 40.0
                        },
                        new
                        {
                            Id = 2,
                            data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            miasto = "Kraków",
                            temperatura = 15.119999999999999,
                            wiatr = 0.40000000000000002,
                            wilgotnosc = 61.0
                        },
                        new
                        {
                            Id = 3,
                            data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            miasto = "Łódź",
                            temperatura = 10.5,
                            wiatr = 1.7,
                            wilgotnosc = 52.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
